# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SawitMetric
                                 A QGIS plugin
 Deep Learning-based Oil Palm Detection & Counting.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-22
        copyright            : (C) 2026 by Kenzie Farrel
        email                : kenziefarrel81@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Kenzie Farrel'
__date__ = '2026-04-22'
__copyright__ = '(C) 2026 by Kenzie Farrel'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SawitMetric class from file SawitMetric.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sawit_metric import SawitMetricPlugin
    return SawitMetricPlugin()
