# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SawitMetric
                                 A QGIS plugin
 Deep Learning-based Oil Palm Detection & Counting.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-22
        copyright            : (C) 2026 by Kenzie Farrel
        email                : kenziefarrel81@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Kenzie Farrel'
__date__ = '2026-04-22'
__copyright__ = '(C) 2026 by Kenzie Farrel'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import numpy as np
from ultralytics import YOLO
from qgis.core import (QgsFeature, QgsGeometry, QgsPointXY, QgsFields, QgsField)
from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer, # For the satellite image
                       QgsProcessingParameterFile,        # For the .pt model
                       QgsProcessingParameterNumber,      # For Confidence threshold
                       QgsProcessingParameterFeatureSink, # For the output points
                       QgsFeatureSink,
                       QgsRectangle,
                       QgsWkbTypes,
                       QgsSpatialIndex,
                       QgsDistanceArea)


class SawitMetricAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config=None):
        # Input Satellite/Drone Imagery (.tif)
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input Raster Imagery')
            )
        )

        # YOLOv8 Weights (.pt)
        self.addParameter(
            QgsProcessingParameterFile(
                'MODEL_PATH',
                self.tr('YOLOv8 Model File (.pt)'), 
                extension='pt'
            )
        )

        # Confidence Threshold (Scientific Metric)
        self.addParameter(
            QgsProcessingParameterNumber(
                'CONFIDENCE',
                self.tr('Confidence Threshold'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.25,
                minValue=0.0,
                maxValue=1.0
            )
        )

        # Minimum Distance (NMS)
        self.addParameter(
            QgsProcessingParameterNumber(
                'MIN_DIST',
                self.tr('Minimum Distance Between Trees (meters)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=3.0,
                minValue=0.0
            )
        )

        # Output Point Layer (Detected Trees)
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Detected Palm Trees')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        raster_layer = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        model_path = self.parameterAsFile(parameters, 'MODEL_PATH', context)
        conf_threshold = self.parameterAsDouble(parameters, 'CONFIDENCE', context)
        min_dist = self.parameterAsDouble(parameters, 'MIN_DIST', context)
        
        model = YOLO(model_path)
        
        fields = QgsFields()
        fields.append(QgsField("Confidence", QVariant.Double))
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, fields, QgsWkbTypes.Point, raster_layer.crs())

        provider = raster_layer.dataProvider()
        rows = raster_layer.height()
        cols = raster_layer.width()
        extent = raster_layer.extent()
        
        px_size_x = extent.width() / cols
        px_size_y = extent.height() / rows
        tile_size = 640
        
        all_detections = [] 

        # --- DETECTION PASS ---
        for y in range(0, rows, tile_size):
            for x in range(0, cols, tile_size):
                if feedback.isCanceled(): break

                window_width = min(tile_size, cols - x)
                window_height = min(tile_size, rows - y)
                
                tile_x_min = extent.xMinimum() + (x * px_size_x)
                tile_y_max = extent.yMaximum() - (y * px_size_y)
                tile_x_max = tile_x_min + (window_width * px_size_x)
                tile_y_min = tile_y_max - (window_height * px_size_y)
                tile_rect = QgsRectangle(tile_x_min, tile_y_min, tile_x_max, tile_y_max)

                img_np = np.zeros((window_height, window_width, 3), dtype=np.uint8)
                for band in range(1, 4):
                    block = provider.block(band, tile_rect, window_width, window_height)
                    ptr = block.data()
                    line_array = np.frombuffer(ptr, dtype=np.uint8).reshape((window_height, window_width))
                    img_np[:, :, band-1] = line_array

                results = model.predict(source=img_np, conf=conf_threshold, save=False)
                
                for r in results:
                    for box in r.boxes:
                        coords = box.xywh[0]
                        pixel_x = x + coords[0].item()
                        pixel_y = y + coords[1].item()
                        
                        map_x = extent.xMinimum() + (pixel_x * px_size_x)
                        map_y = extent.yMaximum() - (pixel_y * px_size_y)
                        
                        all_detections.append({
                            'point': QgsPointXY(map_x, map_y),
                            'conf': float(box.conf[0])
                        })

        # --- REFINED NMS PASS (Degrees to Meters) ---
        feedback.pushInfo(f"Filtering {len(all_detections)} detections for EPSG:4326...")
        all_detections.sort(key=lambda x: x['conf'], reverse=True)
        
        # Initialize the distance tool
        d = QgsDistanceArea()
        d.setSourceCrs(raster_layer.crs(), context.transformContext())
        d.setEllipsoid(context.ellipsoid()) # Use project ellipsoid (usually WGS84)
        
        spatial_index = QgsSpatialIndex()
        final_points = []
        
        # Approximate degree window to limit search (0.0001 deg is ~11m)
        search_window = 0.0001 

        for i, det in enumerate(all_detections):
            search_rect = QgsRectangle(
                det['point'].x() - search_window, det['point'].y() - search_window,
                det['point'].x() + search_window, det['point'].y() + search_window
            )
            
            # Find nearby candidates
            potential_neighbor_ids = spatial_index.intersects(search_rect)
            
            keep = True
            for n_idx in potential_neighbor_ids:
                # Calculate ACTUAL distance in meters
                neighbor_pt = all_detections[n_idx]['point']
                dist_m = d.measureLine(det['point'], neighbor_pt)
                
                if dist_m < min_dist:
                    keep = False
                    break
            
            if keep:
                final_points.append(det)
                f = QgsFeature()
                f.setGeometry(QgsGeometry.fromPointXY(det['point']))
                f.setId(i)
                spatial_index.addFeature(f)

        # Write final results
        for p in final_points:
            feat = QgsFeature(fields)
            feat.setGeometry(QgsGeometry.fromPointXY(p['point']))
            feat.setAttribute("Confidence", p['conf'])
            sink.addFeature(feat, QgsFeatureSink.FastInsert)

        feedback.pushInfo(f"NMS Complete. Kept {len(final_points)} trees.")
        return {self.OUTPUT: dest_id}
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Detect and Count Palm Trees'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Inventory Tools'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SawitMetricAlgorithm()
